name: "Terraform Pipeline Provision EC2"

on:
  push:
    branches: ['master', 'main']
  pull_request:
    branches: ['master', 'main']

permissions:
  contents: write

env:
  # verbosity setting for Terraform logs
    TF_LOG: INFO
    # Credentials for deployment to AWS
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    TF_CLOUD_ORGANIZATION: "prodxcloud"
    TF_WORKSPACE: "prodxcloud"
    TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    CONFIG_DIRECTORY: "./deployments/terraform/terraform-aws-ec2-tf/terraform/"

Jobs:
  terraform:
    name: "Terraform Pipeline Provision EC2 with TF Cloud"
    runs-on: ubuntu-latest
    defaults:
      runs:
        shell: bash
        # We keep Terraform files in the terraform directory
        working-directory: ./deployments/terraform/terraform-aws-ec2-tf/terraform

    steps:
      - name: Checkout the repository to the runner
        uses: action/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
